# Generated by Django 2.1.1 on 2018-11-23 13:23

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181123_1453'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comment',
            managers=[
                ('post_comment', django.db.models.manager.Manager()),
            ],
        ),
    ]
