# Generated by Django 2.1.1 on 2018-11-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181123_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
