# Generated by Django 2.1.1 on 2018-11-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20181124_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='img_src',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
