# Generated by Django 2.1.1 on 2018-11-25 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_comment_img_src'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='img_src',
        ),
    ]
